#!/usr/bin/env node
const { execSync } = require('child_process');
const fs = require('fs');

function run(cmd) {
  try {
    return execSync(cmd, { encoding: 'utf8' }).trim();
  } catch (e) {
    return null;
  }
}

const commit = run('git rev-parse --short HEAD') || 'unknown';
let date = run("git show -s --format=%ci HEAD");
if (!date) {
  date = new Date().toISOString();
}
// keep minute precision
const dt = new Date(date);
const yyyy = dt.getFullYear();
const mm = String(dt.getMonth() + 1).padStart(2, '0');
const dd = String(dt.getDate()).padStart(2, '0');
const hh = String(dt.getHours()).padStart(2, '0');
const min = String(dt.getMinutes()).padStart(2, '0');
const formatted = `${yyyy}-${mm}-${dd} ${hh}:${min}`;

const content = `// generated by scripts/generateBuildInfo.js
export const COMMIT_HASH = '${commit}';
export const COMMIT_DATE = '${formatted}';
`;

fs.mkdirSync('src', { recursive: true });
fs.writeFileSync('src/build-info.ts', content);
console.log('Wrote src/build-info.ts:', commit, formatted);
